"""All carrier design parameters in one place.

Measured board values are LOADED from analysis/*.json (generated by
scripts/analyze_step.py / scripts/analyze_dxf.py from the manufacturer
STEP/DXF). Only design decisions live here as literals.

Coordinate system (carrier): origin at footprint center, z=0 is the build
plate / carrier underside. +Y = board long axis. A7670 section on +X,
T-SimHat section on -X, wiring/service gap between them.
"""

from __future__ import annotations

import json
import os

ANALYSIS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "analysis")


def _load(name):
    with open(os.path.join(ANALYSIS_DIR, name)) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Measured reference geometry (do not edit — regenerate analysis instead)
# ---------------------------------------------------------------------------

class Measured:
    a7670 = _load("a7670_geometry.json")
    a7670_dxf = _load("a7670_dxf.json")
    simhat = _load("simhat_geometry.json")

    # A7670 PCB outline (STEP cross-section), STEP-native coordinates
    a7670_pcb_x0 = a7670["pcb_outline"]["bbox"]["xmin"]
    a7670_pcb_y0 = a7670["pcb_outline"]["bbox"]["ymin"]
    a7670_pcb_w = 33.071            # DXF dimension 33.071 (cross-checks STEP)
    a7670_pcb_l = 110.541           # STEP outline dy
    a7670_pcb_t = 1.2               # STEP slab thickness

    # A7670 mounting holes: DXF-dimensioned Ø1.7296 at 4 corners
    # (STEP shows Ø1.70 cylinders at the same centers - same feature)
    a7670_hole_d = 1.7296
    a7670_holes_rel = [             # (x, y) relative to PCB bbox min corner
        (267.462 - a7670_pcb_x0, 115.388 - a7670_pcb_y0),   # near-left
        (295.199 - a7670_pcb_x0, 115.438 - a7670_pcb_y0),   # near-right
        (295.199 - a7670_pcb_x0, 220.975 - a7670_pcb_y0),   # far-right
        (267.487 - a7670_pcb_x0, 220.975 - a7670_pcb_y0),   # far-left
    ]

    # T-SimHat PCB (STEP), board-local coords x[-16.5,16.5], y[-94.8,0]
    simhat_pcb_w = 33.0
    simhat_pcb_l = 94.8
    simhat_pcb_t = 1.0              # STEP slab; VERIFY with calipers (may be 1.6)

    # T-SimHat STEP component zones, STEP-native (x, y); y=0 is the end that
    # faces the snap clips on the carrier. Derived from component solids.
    simhat_relay_zone = (-16.5, -29.2, 0.0, -6.5, 18.25)    # x0, y0, x1, y1, h
    simhat_tblock_zone = (5.5, -15.8, 16.5, 0.0, 13.8)
    simhat_header_zone_x = (14.0, 16.5)                       # both edges
    simhat_header_zone_y = (-94.7, -54.0)                     # far (lip) end
    simhat_header_h = 8.1                                      # above PCB when flipped


# ---------------------------------------------------------------------------
# Fasteners
# ---------------------------------------------------------------------------

A7670_SCREW = "M1.6"                # PCB hole Ø1.73 (DXF) -> M1.6 passes w/ clearance
A7670_PILOT_D = 1.30                # self-tap pilot for M1.6 in PETG
A7670_STANDOFF_OD = 4.6             # >= 1.6mm wall around pilot
ENCLOSURE_SCREW = "M3"
EAR_SLOT_W = 3.4                    # M3 clearance slot width
EAR_SLOT_L = 7.5                    # slot length = adjustable position range

# ---------------------------------------------------------------------------
# Base frame
# ---------------------------------------------------------------------------

BASE_T = 3.2                        # base plate/rail thickness
RAIL_W = 3.2                        # structural rail/rib width
FRAME_MARGIN = 6.5                  # rail setback from board edges
OUTER_CORNER_R = 6.0                # rounded external corners
RIB_PITCH = 38.0                    # max unsupported span between cross ribs
BOARD_GAP = 12.0                    # service gap between the two boards

# ---------------------------------------------------------------------------
# A7670 mounting section (board sits component-up on 4 standoffs)
# ---------------------------------------------------------------------------

A7670_STANDOFF_H = 13.0             # base_top(3.2) + shield 8.4 + 1.4 clearance.
                                    # If 16mm stacking-header pins are soldered
                                    # to the bottom of the board, set to 21.0.

# ---------------------------------------------------------------------------
# T-SimHat snap-in cage (board mounted FLIPPED: relay side down, pins up)
# Board-local pad coordinates: (u, v); u from board center x, v from clip end (y=0)
# ---------------------------------------------------------------------------

SIMHAT_SUPPORT_H = 23.0             # pad top height; >= BASE_T + relay 18.25 + 1.5
SIMHAT_PCB_XY_CLEAR = 0.30          # per-side XY clearance around PCB edges
SIMHAT_PCB_T_CLEAR = 0.20           # vertical clearance in lip/hook gaps
# Pads sit on bare laminate only. Verified against ALL 77 above-PCB solids:
# the only 7mm+ free window on BOTH u strips is v 31.0-50.5. Pads must ALSO
# stay clear of the removal slide path: down-facing SMDs (v 50.5-53.8,
# u +/-1.6-6) sweep 3.6mm toward the clip end during board removal, so pads
# top out at v 45 (SMD sweep floor v 46.9). Blocked: relay v 6.5-29.2,
# terminal v 0-15.8, SMD clusters v 50.5+.
SIMHAT_PADS_UV = [(-3.5, 34.5), (3.5, 34.5), (-3.5, 42.0), (3.5, 42.0)]
SIMHAT_PAD_SIZE = 6.0               # square support pads on exposed laminate
SIMHAT_RELAY_CLEAR = 1.75           # air gap under deepest down-facing part

# fixed capture lip (far end, 2 segments avoiding up-facing SMD parts)
SIMHAT_LIP_SEGMENTS_U = [(-13.5, -9.0), (9.0, 13.5)]   # u ranges of lip rails
SIMHAT_LIP_ENGAGE = 2.6             # how far lip ledge reaches over PCB top
SIMHAT_LIP_T = 2.4                  # lip ledge thickness

# snap clips (near end corners; XY-plane flexure, bending about Z)
SIMHAT_HOOK_ENGAGE = 1.0            # ledge reach past PCB edge face
SIMHAT_HOOK_T = 2.2                 # hook ledge vertical thickness
SIMHAT_HOOK_REACH_V = 2.4           # ledge reach onto PCB top (in v)
SIMHAT_HOOK_LEAD_CHAMFER = 0.8   # plan-view ramp on hook inner corner; turns
                                 # corner-on-corner insertion contact into a
                                 # smooth ramp ride (same corner acts on release)
SIMHAT_HOOK_LEAD_ANGLE = 40.0       # informational: atan(chamfer c/c) intent
SIMHAT_ARM_LEN = 14.0               # cantilever length root->hook center
SIMHAT_ARM_W = 6.0                  # arm depth in Z
SIMHAT_ARM_T = 2.0                  # arm thickness in u (bending direction)
SIMHAT_ARM_ROOT_FILLET = 2.0        # fillet where arm meets anchor
SIMHAT_ARM_DEFLECT = 1.05           # lateral deflection to clear PCB edge
SIMHAT_RELEASE_TAB_H = 7.0          # finger fin height above arm
SIMHAT_RELEASE_TAB_T = 2.0          # fin thickness

# XY locating fences along long edges, (side, v) side=-1 left/+1 right
SIMHAT_FENCES = [(-1, 45.0), (1, 16.0), (1, 74.0)]
SIMHAT_FENCE_T = 2.4
SIMHAT_FENCE_ENGAGE_H = 4.0         # wall height above PCB underside

# ---------------------------------------------------------------------------
# Wiring / strain relief
# ---------------------------------------------------------------------------

TIE_SLOT_W = 3.6                    # cable tie width clearance
TIE_SLOT_L = 7.0                    # tie loop length clearance
TIE_SLOTS = [                       # (x, y) through gap rails, long axis along Y
    (7.0, -42.0), (7.0, -14.0), (7.0, 14.0), (7.0, 42.0),
    (-7.0, -42.0), (-7.0, -14.0), (-7.0, 14.0), (-7.0, 42.0),
]

# ---------------------------------------------------------------------------
# Enclosure mounting interface (parametric ears)
# ---------------------------------------------------------------------------

EARS = {                            # corner -> (dx, dy) direction of ear
    "a7670-near": (+1, -1),
    "a7670-far": (+1, +1),
    "simhat-near": (-1, -1),
    "simhat-far": (-1, +1),
}
EAR_EXT = 11.0                      # how far ear flange reaches beyond outer rail
EAR_W = 16.0                        # ear width
EAR_T = BASE_T                      # ear thickness (flush with base)
EAR_SLOT_ANGLE = 0.0                # 0 = slot long axis along Y; 90 = along X
TAPE_PAD_SIZE = 24.0                # flat VHB landing zones (kept hole-free)
TAPE_PADS = [("a7670-mid", 0.0), ("simhat-mid", 0.0)]

# ---------------------------------------------------------------------------
# LTE sticker antenna slide-in tray (-Y end; slide along sticker SHORT dim)
# LILYGO "full band 698-1710-2690" FPC sticker, SMA coax. No manufacturer CAD
# exists -> CALIPER the sticker and set ANT_SLIDE/ANT_W before printing.
# Defaults assume ~50 x 45 mm class, slid along its 45 mm dimension.
# ---------------------------------------------------------------------------

ANT_ENABLED = True
ANT_SLIDE = 45.0          # sticker dimension along slide direction (mm)
ANT_W = 50.0              # sticker dimension across channels (mm)
ANT_X_C = 5.0             # tray center X (over gap + A7670 side, clear of cage)
ANT_SIDE_CLEAR = 0.5      # per-side clearance between sticker and channel walls
ANT_FLOOR_T = 1.2         # tray floor thickness
ANT_WALL_T = 2.4          # channel wall thickness
ANT_WALL_H = 4.5          # channel wall height above plate
ANT_STOP_T = 2.4          # end-stop wall thickness
ANT_ENTRY_CHAMFER = 1.5   # lead-in chamfer on channel mouths
ANT_COAX_NOTCH_W = 5.0    # coax pass-through notch in the -Y ring rail

# ---------------------------------------------------------------------------
# Connector service envelopes (validated keep-clear volumes, carrier coords)
# Derived from measured STEP islands: USB-C on +Y edge at x[13,31] z[13,16];
# both SMA jacks on +X edge at y[-21,-3] z[13,15]; envelopes add plug bodies.
# ---------------------------------------------------------------------------

SERVICE_ENVELOPES = {
    "usb_c_plug":       (19.0, 55.0, 37.5, 68.0, 12.0, 18.0),
    "sma_antenna_conn": (40.0, -22.0, 56.0, -2.0, 12.0, 16.5),
    "sim_tray_swap":    (10.0, 30.0, 40.0, 58.0, 14.0, 24.0),
    "battery_jst":      (12.0, -14.0, 30.0, 4.0, 14.0, 24.0),
}

# ---------------------------------------------------------------------------
# Print envelope (Bambu A1 mini safety target)
# ---------------------------------------------------------------------------

MAX_XY = 175.0

# ---------------------------------------------------------------------------
# Derived layout helpers
# ---------------------------------------------------------------------------

def a7670_cx(gap=BOARD_GAP):
    """X center of A7670 section."""
    return +(gap / 2 + Measured.a7670_pcb_w / 2)


def simhat_cx(gap=BOARD_GAP):
    return -(gap / 2 + Measured.simhat_pcb_w / 2)


def frame_y_half(margin=FRAME_MARGIN):
    return max(Measured.a7670_pcb_l, Measured.simhat_pcb_l) / 2 + margin
