"""All carrier design parameters in one place.

Measured board values are LOADED from analysis/*.json (generated by
scripts/analyze_step.py / scripts/analyze_dxf.py from the manufacturer
STEP/DXF). Only design decisions live here as literals.

Coordinate system (carrier): origin at footprint center, z=0 is the build
plate / carrier underside. +Y = board long axis. A7670 section on +X,
T-SimHat section on -X, wiring/service gap between them.
"""

from __future__ import annotations

import json
import os

ANALYSIS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "analysis")


def _load(name):
    with open(os.path.join(ANALYSIS_DIR, name)) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Measured reference geometry (do not edit — regenerate analysis instead)
# ---------------------------------------------------------------------------

class Measured:
    a7670 = _load("a7670_geometry.json")
    a7670_dxf = _load("a7670_dxf.json")
    simhat = _load("simhat_geometry.json")

    # A7670 PCB outline (STEP cross-section), STEP-native coordinates
    a7670_pcb_x0 = a7670["pcb_outline"]["bbox"]["xmin"]
    a7670_pcb_y0 = a7670["pcb_outline"]["bbox"]["ymin"]
    a7670_pcb_w = 33.071            # DXF dimension 33.071 (cross-checks STEP)
    a7670_pcb_l = 110.541           # STEP outline dy
    a7670_pcb_t = 1.2               # STEP slab thickness

    # A7670 mounting holes, board-local: measured directly off the placed
    # manufacturer STEP (Ø1.70 corner cylinders, inverse-mapped). The DXF
    # Ø1.7296 DIMENSION defpoints and the analysis JSON candidates are
    # callout anchors offset ~(+0.31,-0.22) from the true centers - the
    # boolean interference check caught the discrepancy when snap plugs
    # were placed on the DXF positions. These four values are
    # authoritative; grid 27.71 x 105.56.
    a7670_holes_rel = [
        (2.896, 2.036),     # near-left  (clip end)
        (30.633, 2.087),    # near-right
        (2.922, 107.624),   # far-left   (USB end)
        (30.633, 107.624),  # far-right
    ]

    # T-SimHat PCB (STEP), board-local coords x[-16.5,16.5], y[-94.8,0]
    simhat_pcb_w = 33.0
    simhat_pcb_l = 94.8
    simhat_pcb_t = 1.25             # PHYSICAL (coupon stair: free in 1.4,
                                    # tight in 1.2). STEP models 1.0 = bare
                                    # laminate without mask/soldermask. The
                                    # coupon bay's 1.2mm slot gripped the
                                    # 1.25mm board "perfectly firm".

    # T-SimHat STEP component zones, STEP-native (x, y); y=0 is the end that
    # faces the snap clips on the carrier. Derived from component solids.
    simhat_relay_zone = (-16.5, -29.2, 0.0, -6.5, 18.25)    # x0, y0, x1, y1, h
    simhat_tblock_zone = (5.5, -15.8, 16.5, 0.0, 13.8)
    simhat_header_zone_x = (14.0, 16.5)                       # both edges
    simhat_header_zone_y = (-94.7, -54.0)                     # far (lip) end
    simhat_header_h = 8.1                                      # above PCB when flipped
    # Non-circular PCB cutouts found in the slab cross-section (missed by
    # the cylinder scan; user-confirmed on the physical board):
    simhat_cutout_relay = (-15.25, -30.20, -1.35, -17.60)     # 13.9x12.6 oval INSIDE relay footprint - keep-out
    simhat_cutout_slot = (2.50, -18.35, 13.40, -16.45)        # 10.9x1.9 slot past terminal


# ---------------------------------------------------------------------------
# Build profile: "full" = production carrier; "low" = ~12 mm quick-print
# fit-check slab (desk check of hole pattern / pad window / snap feel, and
# wall-mountable via the M3 ear slots against a box wall). Relay overhangs
# below the low slab - test the SimHat snap at a desk edge.
# ---------------------------------------------------------------------------

PROFILE = "full"

# ---------------------------------------------------------------------------
# Fasteners
# ---------------------------------------------------------------------------

# Mounting: "screws" is the default after the v0.3 print (user report:
# snap plugs did not hold reliably; screws are deterministic). "snap_plugs"
# stays available as the screwless variant.
A7670_MOUNT = "screws"                # "snap_plugs" | "screws"
PLUG_SHAFT_D = 1.10                   # clears the Ø1.35 STEP drill 0.125/side
PLUG_FIN_DS = (1.55, 1.65)            # stacked retention fins above the PCB;
                                      # each passes the ~Ø1.4 plated hole with
                                      # <=0.125mm/finger flex (christmas-tree
                                      # board-lock pattern)
PLUG_FIN_H = 0.35                     # fin ring height
PLUG_FIN_PITCH = 0.35                 # fin vertical spacing
PLUG_FIN_LEAD = 0.25                  # 45-deg-ish lead-in per fin
PLUG_SLOT_W = 0.7                     # cross-slot width -> 4 fingers
A7670_STANDOFF_OD = 4.6               # boss footprint under each plug
A7670_PILOT_D = 1.30                  # screws mode: self-tap pilot
ENCLOSURE_SCREW = "M3"
EAR_SLOT_W = 3.4                      # M3 clearance slot width
EAR_SLOT_L = 7.5                      # slot length = adjustable position range

# ---------------------------------------------------------------------------
# Base frame
# ---------------------------------------------------------------------------

BASE_T = 3.2                        # base plate/rail thickness
RAIL_W = 3.2                        # structural rail/rib width
FRAME_MARGIN = 6.5                  # rail setback from board edges
OUTER_CORNER_R = 6.0                # rounded external corners
RIB_PITCH = 38.0                    # max unsupported span between cross ribs

# 16 -> 20 mm wiring channel: easier fingers + SMA plug clearance between
# the boards; USB-C is on the A7670 -Y end (points AWAY from the SimHat).
BOARD_GAP = 20.0                    # service gap between the two boards

# ---------------------------------------------------------------------------
# A7670 section (board component-up on 4 screw standoffs)
# ---------------------------------------------------------------------------

# Rotate board 180 deg about Z: pin-header rails land at the -Y end, the
# same end as the SimHat's up-facing sockets -> jumpers ~15-25 mm instead
# of ~120 mm; SMA jacks then face the wiring gap.
A7670_ROT_180 = True

# 18650 + holder hangs below the PCB along the board centerline. 25 mm
# clears: base 3.2 + cell/holder ~20.5 + air. No battery holder -> 13.0.
A7670_STANDOFF_H = 25.0 if PROFILE == "full" else 9.0
A7670_BATTERY_KEEP_W = 20.0         # 18650 cell 18.6 + holder walls
A7670_BATTERY_KEEP_L = 71.0         # 65 cell + clip ends

# ---------------------------------------------------------------------------
# T-SimHat snap-in cage (board mounted FLIPPED: relay side down, pins up)
# Board-local pad coordinates: (u, v); u from board center x, v from clip end (y=0)
# ---------------------------------------------------------------------------

SIMHAT_SUPPORT_H = (23.0 if PROFILE == "full" else 9.0)
SIMHAT_CLIPS_ENABLED = PROFILE == "full"
SIMHAT_PCB_XY_CLEAR = 0.30          # per-side XY clearance around PCB edges
SIMHAT_PCB_T_CLEAR = 0.20           # vertical clearance in lip/hook gaps
# Pads sit on bare laminate only. Verified against ALL 77 above-PCB solids:
# the only 7mm+ free window on BOTH u strips is v 31.0-50.5. Pads must ALSO
# stay clear of the removal slide path (down-facing SMDs v 50.5-53.8 sweep
# 3.6mm toward the clip end) AND of SMD solder fillets: u +/-2.75 centers
# pads in the free strip, giving ~2.0mm edge distance to the SMD bodies at
# u +/-7.2 (was 0.7mm at u +/-3.5 - user-flagged solder-pad risk).
SIMHAT_PADS_UV = [(-2.75, 34.5), (2.75, 34.5), (-2.75, 42.0), (2.75, 42.0)]
SIMHAT_PAD_SIZE = 6.0               # square support pads on exposed laminate
SIMHAT_RELAY_CLEAR = 1.75           # air gap under deepest down-facing part

# fixed capture lip (far end, 2 segments avoiding up-facing SMD parts)
SIMHAT_LIP_SEGMENTS_U = [(-13.5, -9.0), (9.0, 13.5)]   # u ranges of lip rails
SIMHAT_LIP_ENGAGE = 2.6             # how far lip ledge reaches over PCB top
SIMHAT_LIP_T = 2.4                  # lip ledge thickness

# snap clips (near end corners; XY-plane flexure, bending about Z)
SIMHAT_HOOK_ENGAGE = 1.3            # ledge reach past PCB edge face
                                     # (1.0 printed loose per v0.3 feedback)
SIMHAT_HOOK_T = 2.2                 # hook ledge vertical thickness
SIMHAT_HOOK_REACH_V = 2.4           # ledge reach onto PCB top (in v)
SIMHAT_HOOK_LEAD_CHAMFER = 0.8   # plan-view ramp on hook inner corner; turns
                                 # corner-on-corner insertion contact into a
                                 # smooth ramp ride (same corner acts on release)
SIMHAT_HOOK_LEAD_ANGLE = 40.0       # informational: atan(chamfer c/c) intent
SIMHAT_ARM_LEN = 14.0               # cantilever length root->hook center
SIMHAT_ARM_W = 6.0                  # arm depth in Z
SIMHAT_ARM_T = 2.0                  # arm thickness in u (bending direction)
SIMHAT_ARM_ROOT_FILLET = 2.0        # fillet where arm meets anchor
SIMHAT_ARM_DEFLECT = 1.05           # lateral deflection to clear PCB edge
SIMHAT_RELEASE_TAB_H = 7.0 if PROFILE == "full" else 3.0   # fin above arm
SIMHAT_RELEASE_TAB_T = 2.0          # fin thickness
SIMHAT_ARM_PEDESTAL = True          # printable support wall under the arm
                                    # free span; 0.3mm air gap keeps the XY
                                    # flexure unstiffened - it only carries
                                    # the arm's first print layer
SIMHAT_PED_T = 1.2                  # pedestal thickness (u), < arm thickness
SIMHAT_PED_GAP = 0.3                # air gap between pedestal top and arm
SIMHAT_ARM_ROOT_GUSSET = 1.6        # plan-view triangular gusset at the arm
                                    # root; blends the flexure into the anchor
                                    # (printed stress relief in lieu of an
                                    # OCC fillet, which fails on these prisms)

# XY locating fences: (side, v_center, half_len, bite). The board slides
# +-3.6 mm in v during insert/removal, so every edge-FLUSH part (relay
# v 6.5..29.2, CAN/RS485 v 37..49.4, header sockets v 54..94.7 -- all
# exactly u=16.5) sweeps through any fence window it can reach. A biting
# face (SIMHAT_FENCE_BITE inside the edge plane) therefore needs a window
# with 3.6 mm sweep margin to the next flush part on BOTH sides -- which
# only exists on -u (nearest flush part there is CAN/RS485 at v 37):
#   -u: v 4.5..16.5, bite=True (friction grip, sweep margin 16.9 mm)
#   +u: v 30.2..36.0, bite=False (locator only; between relay and
#       CAN/RS485 at seat, 0.3 clearance lets flush parts pass on slide)
SIMHAT_FENCES = [(-1, 10.5, 6.0, True), (1, 33.1, 2.9, False)]
SIMHAT_FENCE_T = 2.4
SIMHAT_FENCE_BITE = 0.5   # fence face intrudes past the nominal edge
                           # position by (BITE - XY_CLEAR) = 0.2 mm/side:
                           # user-requested friction bite against the PCB
SIMHAT_FENCE_ENGAGE_H = 4.0         # wall height above PCB underside
SIMHAT_END_PLAY = 0.10    # board end faces vs lip wall / clip arm faces
                           # (was the PCB_XY_CLEAR 0.3 -- printed loose,
                           # board rattled in v; 0.1 snugs both ends)

# ---------------------------------------------------------------------------
# Wiring / strain relief
# ---------------------------------------------------------------------------

TIE_SLOT_W = 3.6                    # cable tie width clearance
TIE_SLOT_L = 7.0                    # tie loop length clearance
# Slots live ON the gap rails: x = +/-(gap/2 + 0.4 + RAIL_W/2), computed
# here from BOARD_GAP so they follow the rails when the gap changes.
_gap_rail_x = BOARD_GAP / 2 + 0.4 + RAIL_W / 2
TIE_SLOTS = [
    (_gap_rail_x, -42.0), (_gap_rail_x, -14.0),
    (_gap_rail_x, 21.0), (_gap_rail_x, 42.0),
    (-_gap_rail_x, -42.0), (-_gap_rail_x, -14.0),
    (-_gap_rail_x, 21.0), (-_gap_rail_x, 42.0),
]

# ---------------------------------------------------------------------------
# Enclosure mounting interface (parametric ears)
# ---------------------------------------------------------------------------

EARS = {                            # corner -> (dx, dy) direction of ear;
    # full profile uses 4 corners when the antenna is under the battery
    # (no tray mouth to avoid); end_tray swaps the two -Y corners for
    # stop-wall tabs via holder._ear_geometry()
    "a7670-near": (+1, -1),
    "a7670-far": (+1, +1),
    "simhat-near": (-1, -1),
    "simhat-far": (-1, +1),
}
EAR_EXT = 11.0                      # how far ear flange reaches beyond outer rail
EAR_W = 16.0                        # ear width
EAR_T = BASE_T                      # ear thickness (flush with base)
EAR_SLOT_ANGLE = 0.0                # 0 = slot long axis along Y; 90 = along X
TAPE_PAD_SIZE = 24.0                # flat VHB landing zones (kept hole-free)
TAPE_PADS = [("a7670-mid", 0.0), ("simhat-mid", 0.0)]

# ---------------------------------------------------------------------------
# LTE sticker antenna position + channel geometry.
# User-measured: ~110 x 20 mm sticker, coax pigtail enters ~20 mm into one
# end (that end goes in LAST, at the mouth), 10-15 cm coax.
#
# ANT_POS = "under_battery" (default): sticker slides flat UNDER the A7670
#   on a continuous base strip (z 3.2) in the 1.3 mm gap below the 18650
#   holder (battery bottom z 4.5). Side guides only - top fully open.
#   Footprint shrinks ~34 mm in Y (no end appendix). RF trade-off: directly
#   under a battery+PCB costs typically 3-10 dB (Antenova/Digi guidance);
#   accepted for a shed relay inside a plastic enclosure.
# ANT_POS = "end_tray": the v0.3 slide-in tray appended beyond the -Y rail.
# ---------------------------------------------------------------------------

ANT_POS = "under_battery"
ANT_SLIDE = 110.0        # sticker long dimension (along Y when under_battery)
ANT_W = 20.0             # sticker width (across the channel)
ANT_X_C = None           # under_battery: centered on the A7670 (auto)
ANT_SIDE_CLEAR = 0.6     # lateral clearance per side (coupon: fits 19.8-20.2)
ANT_CABLE_ENTRY = 20.0   # pigtail-inside-sticker length; sits in the mouth
ANT_GUIDE_SLOPE_DEG = 80.0   # inner guide faces lean out 10 deg from vertical
ANT_GUIDE_H = 2.5        # guide height (sticker only needs edge capture;
                         # shed-box build -> shorter = faster, less plastic)
ANT_GUIDE_T = 2.4        # guide base thickness
ANT_STOP_Y = 52.5        # stop block inner face (+Y end of channel)
ANT_FLOOR_T = 3.2        # base strip height under the channel
ANT_CENTER_RAIL_W = 3.0  # sparse floor: center rail + end ties instead of a
                         # solid 110x26 slab (sticker is stiff enough to
                         # slide on a rail; saves ~7 g and print time)
ANT_COAX_NOTCH_W = 5.0   # end_tray only: coax pass-through in the -Y rail

# end_tray geometry (legacy, kept as the alternative position)
ANT_TRAY_EXT = 24.0      # how far the end tray reaches beyond the -Y rail
ANT_TRAY_WALL_H = 4.5
ANT_TRAY_WALL_T = 2.4
ANT_TRAY_STOP_T = 2.4
ANT_TRAY_ENTRY_CHAMFER = 1.5
ANT_STOP_TAB_X = (-35.0, 35.0)
ANT_STOP_TAB_EXT = 9.0
ANT_CABLE_L = 120.0       # coax length estimate (doc/coil-planning param)

# ---------------------------------------------------------------------------
# Connector service envelopes (keep-clear volumes). A7670 envelopes are in
# board-local coords (x from PCB left edge, y from PCB bottom edge, z from
# PCB top face) and pass through a7670_local_to_carrier(), which applies
# the A7670_ROT_180 mapping - never hardcode rotated coords.
# SimHat envelopes are in flipped board-local (u, -y, z-from-PCB-top).
# ---------------------------------------------------------------------------

SERVICE_ENVELOPES_A7670 = {
    "usb_c_plug":       (8.0, 101.0, 27.0, 113.0, 0.0, 6.0),
    "sma_antenna_conn": (27.0, 30.0, 40.0, 55.0, -1.0, 5.0),
    "sim_tray_swap":    (10.0, 80.0, 40.0, 98.0, 1.0, 11.0),
    "battery_jst":      (8.0, 32.0, 20.0, 52.0, 0.0, 8.0),
}
SERVICE_ENVELOPES_SIMHAT = {
    "header_jumpers":   (-16.5, -94.7, 16.5, -50.0, 1.0, 15.0),
    "relay_terminals":  (-16.5, -29.2, 16.5, 0.0, -18.25, -15.0),
}

# ---------------------------------------------------------------------------
# Print envelope (Bambu A1 mini safety target)
# ---------------------------------------------------------------------------

MAX_XY = 175.0

# ---------------------------------------------------------------------------
# Derived layout helpers
# ---------------------------------------------------------------------------

def a7670_cx(gap=BOARD_GAP):
    """X center of A7670 section."""
    return +(gap / 2 + Measured.a7670_pcb_w / 2)


def simhat_cx(gap=BOARD_GAP):
    return -(gap / 2 + Measured.simhat_pcb_w / 2)


def frame_y_half(margin=FRAME_MARGIN):
    return max(Measured.a7670_pcb_l, Measured.simhat_pcb_l) / 2 + margin


# CARRIER_PROFILE=low env var switches to the 9 mm fit-check template
# (open frame, 9 mm bosses/cage walls, no clips - the coupon covers snap
# feel); explicit PROFILE assignment above still wins when env is unset.
import os as _os  # noqa: E402
if _os.environ.get("CARRIER_PROFILE") == "low" and PROFILE == "full":
    PROFILE = "low"
    A7670_STANDOFF_H = 9.0
    SIMHAT_SUPPORT_H = 9.0
    SIMHAT_CLIPS_ENABLED = False
    ANT_POS = "none"
